FROM alpine:3.5

LABEL maintainer="Ajitem Sahasrabuddhe <me@ajitem.com>"

COPY alpine/scripts /scripts

RUN ls -la scripts

# RUN  /scripts/user.sh \
#     && /scripts/install.sh \
#     && rm -rf /scripts

# COPY alpine/entrypoint /usr/local/bin/

# ENTRYPOINT ["entrypoint"]

# CMD ["php", "-a"]

# USER www-data