version: 2
jobs:
  build:
    steps:
      - checkout
      - run: make build
  push:
    steps:
      - checkout
      - run: make push
workflows:
    version: 2
    build_and_push:
      jobs:
        - build:
            filters:
              branches:
                only: master
        - test:
            requires:
              - build
            filters:
              branches:
                only: master
  